// Copyright (c) 2026 Ivan Tugay
// SPDX-License-Identifier: GPL-3.0-or-later
// Licensed under GPL-3.0 or later; see https://www.gnu.org/licenses/gpl-3.0.html

// The desktop token build (DS§2, T37.17): Style Dictionary reads the DTCG 2025.10 files in `tokens/`
// and writes `Tokens.swift` plus `Colors.xcassets` into CoxUI and `tokens/tokens.css` for the mockups.
// Run through `just desktop-tokens`; CI re-runs it and fails on any diff, so the JSON is the only
// thing a person edits.
//
// Each `tokens/color.<mode>.json` holds the same roles for one appearance. The `cox/mode` parser
// nests a file under its mode so the modes do not collide as one path, and the outputs pick them
// apart again: one colorset per role with an entry per appearance, one CSS selector per mode.
import StyleDictionary from 'style-dictionary';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const swiftDir = join(here, '../macos/Packages/CoxUI/Sources/CoxUI/Tokens/');
const cssDir = join(here, 'tokens/');
const HEADER = 'Generated by desktop/design/style-dictionary.config.mjs from desktop/design/tokens (`just desktop-tokens`). Do not edit.';

// Asset-catalog appearances per colour mode; `light` is the Any entry. A `-hc` file is optional
// and adds the Increase Contrast variant; light and dark are required for every role.
const APPEARANCES = {
  light: [],
  dark: [{ appearance: 'luminosity', value: 'dark' }],
  'light-hc': [{ appearance: 'contrast', value: 'high' }],
  'dark-hc': [
    { appearance: 'luminosity', value: 'dark' },
    { appearance: 'contrast', value: 'high' },
  ],
};
// The mockups opt into High Contrast with an `hc` class next to `dark`.
const CSS_SELECTORS = { light: ':root', dark: '.dark', 'light-hc': '.hc', 'dark-hc': '.dark.hc' };

// Swift type per base group. Font, Material and Elevation would shadow SwiftUI's and the
// Foundations modifier's names inside CoxUI, hence the `Token` suffix.
const SWIFT_GROUPS = {
  space: 'Space',
  radius: 'Radius',
  size: 'Size',
  font: 'FontToken',
  elevation: 'ElevationToken',
  motion: 'Motion',
  material: 'MaterialToken',
};

const fail = (msg) => {
  throw new Error(`desktop tokens: ${msg}`);
};
const isMode = (token) => token.path[0] in APPEARANCES;
// `$root` is DTCG's token that sits on a group (`accent` next to `accent.soft`); it takes the group's name.
const parts = (path) => path.filter((p) => p !== '$root');
const camel = (path) => parts(path).map((p, i) => (i ? p[0].toUpperCase() + p.slice(1) : p)).join('');
const kebab = (path) => parts(path).join('-');

const srgb = (value, where) => {
  if (value?.colorSpace !== 'srgb' || !/^#[0-9a-f]{6}$/i.test(value.hex ?? '')) {
    fail(`${where}: expected an srgb colour with a #rrggbb hex`);
  }
  const alpha = value.alpha ?? 1;
  if (!(alpha >= 0 && alpha <= 1)) fail(`${where}: alpha ${alpha} is outside 0…1`);
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(value.hex.slice(i, i + 2), 16));
  return { r, g, b, alpha };
};

const px = (dim, where) => {
  if (dim?.unit !== 'px' || typeof dim.value !== 'number') fail(`${where}: expected a px dimension`);
  return dim.value;
};

// Tracking scales with the font size (`.tracking(token.tracking * size)`), so a typography token's
// `letterSpacing` is in em and FontToken keeps the multiple; a missing one means no tracking.
const em = (dim, where) => {
  if (dim === undefined) return 0;
  if (dim?.unit !== 'em' || typeof dim.value !== 'number') fail(`${where}: expected an em letterSpacing`);
  return dim.value;
};

// macOS has named weights only; DS§3.2 reads 650 as semibold, so a weight rounds down.
const WEIGHTS = ['ultraLight', 'thin', 'light', 'regular', 'medium', 'semibold', 'bold', 'heavy', 'black'];
const DESIGNS = { 'SF Pro Text': '.default', 'SF Mono': '.monospaced' };

const swiftValue = {
  dimension: (v, w) => ['CGFloat', String(px(v, w))],
  number: (v, w) => (typeof v === 'number' ? ['Double', String(v)] : fail(`${w}: expected a number`)),
  duration: (v, w) => {
    const scale = { ms: 1000, s: 1 }[v?.unit] ?? fail(`${w}: expected ms or s`);
    return ['TimeInterval', String(v.value / scale)];
  },
  cubicBezier: (v, w) => {
    if (!Array.isArray(v) || v.length !== 4) fail(`${w}: expected four control values`);
    const [x1, y1, x2, y2] = v;
    return ['UnitCurve', `.bezier(startControlPoint: UnitPoint(x: ${x1}, y: ${y1}), endControlPoint: UnitPoint(x: ${x2}, y: ${y2}))`];
  },
  typography: (v, w) => {
    const weight = WEIGHTS[Math.floor(v.fontWeight / 100) - 1] ?? fail(`${w}: weight ${v.fontWeight}`);
    const design = DESIGNS[v.fontFamily?.[0]] ?? fail(`${w}: unknown family ${v.fontFamily?.[0]}`);
    return [
      'FontToken',
      `FontToken(size: ${px(v.fontSize, w)}, weight: .${weight}, design: ${design}, lineHeight: ${v.lineHeight}, tracking: ${em(v.letterSpacing, w)})`,
    ];
  },
  shadow: (v, w) => {
    const layers = (Array.isArray(v) ? v : [v]).map((l) => {
      const c = srgb(l.color, w);
      const color = `Color(.sRGB, red: ${c.r} / 255, green: ${c.g} / 255, blue: ${c.b} / 255, opacity: ${c.alpha})`;
      const dims = ['offsetX', 'offsetY', 'blur', 'spread'].map((k) => px(l[k], `${w}.${k}`));
      return `ShadowLayer(color: ${color}, x: ${dims[0]}, y: ${dims[1]}, blur: ${dims[2]}, spread: ${dims[3]}, inset: ${l.inset === true})`;
    });
    return ['ElevationToken', layers.length ? `ElevationToken(layers: [\n        ${layers.join(',\n        ')},\n    ])` : 'ElevationToken(layers: [])'];
  },
};

const SWIFT_TYPES = `/// A text style (DS§3.2): points at 100 % text size, line height as a multiple, tracking in em.
public struct FontToken: Sendable, Hashable {
    public let size: CGFloat
    public let weight: Font.Weight
    public let design: Font.Design
    public let lineHeight: CGFloat
    public let tracking: CGFloat
}

/// One shadow layer of an elevation level (DS§3.4); an inset layer is the top-edge highlight.
public struct ShadowLayer: Sendable, Hashable {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let inset: Bool
}

/// An elevation level (DS§3.4): its shadow layers, bottom first.
public struct ElevationToken: Sendable, Hashable {
    public let layers: [ShadowLayer]
}
`;

const swiftFormat = ({ dictionary }) => {
  const groups = new Map();
  for (const token of dictionary.allTokens.filter((t) => !isMode(t))) {
    const where = token.path.join('.');
    const type = SWIFT_GROUPS[token.path[0]] ?? fail(`${where}: no Swift group for ${token.path[0]}`);
    const render = swiftValue[token.$type] ?? fail(`${where}: no Swift value for $type ${token.$type}`);
    const [valueType, literal] = render(token.$value, where);
    const doc = token.$description ? `    /// ${token.$description}\n` : '';
    // A group of struct values (`FontToken.body`) extends that struct, so `.textStyle(.body)` reads
    // naturally; any other group is a caseless enum namespace (`Space.m`).
    const extension = valueType === type;
    const decl = extension ? `static let ${camel(token.path.slice(1))}` : `public static let ${camel(token.path.slice(1))}: ${valueType}`;
    if (!groups.has(type)) groups.set(type, { extension, lines: [] });
    groups.get(type).lines.push(`${doc}    ${decl} = ${literal}`);
  }
  const blocks = [...groups].map(([type, { extension, lines }]) => {
    const open = extension ? `public extension ${type}` : `public enum ${type}`;
    return `${open} {\n${lines.join('\n')}\n}\n`;
  });
  // Generated layout is the generator's, not swift-format's (CI `desktop-macos-lint` runs
  // `swift-format lint --strict`), so the file opts out as a whole; one token per line runs
  // past SwiftLint's line length.
  return `// swiftlint:disable line_length\n// ${HEADER}\n// swift-format-ignore-file\n\nimport SwiftUI\n\n${SWIFT_TYPES}\n${blocks.join('\n')}\n// swiftlint:enable line_length\n`;
};

const cssFormat = ({ dictionary }) => {
  const rules = Object.fromEntries(Object.values(CSS_SELECTORS).map((s) => [s, []]));
  for (const token of dictionary.allTokens) {
    const where = token.path.join('.');
    if (isMode(token)) {
      const selector = CSS_SELECTORS[token.path[0]];
      if (!selector) continue;
      const { r, g, b, alpha } = srgb(token.$value, where);
      rules[selector].push(`  --c-${kebab(token.path.slice(2))}: rgba(${r}, ${g}, ${b}, ${alpha});`);
    } else if (token.$type === 'dimension') {
      rules[':root'].push(`  --${kebab(token.path)}: ${px(token.$value, where)}px;`);
    }
  }
  const body = Object.entries(rules).map(([s, lines]) => `${s} {\n${lines.join('\n')}\n}\n`);
  return `/* ${HEADER} */\n\n${body.join('\n')}`;
};

const colorsetsDir = (platform) => join(platform.buildPath, 'Colors.xcassets');
const XCODE_INFO = { author: 'xcode', version: 1 };
const hexByte = (n) => `0x${n.toString(16).padStart(2, '0').toUpperCase()}`;

const colorsets = {
  do: async (dictionary, platform) => {
    const roles = new Map();
    for (const token of dictionary.allTokens.filter(isMode)) {
      const role = camel(token.path.slice(2));
      if (!roles.has(role)) roles.set(role, {});
      roles.get(role)[token.path[0]] = srgb(token.$value, token.path.join('.'));
    }
    const dir = colorsetsDir(platform);
    await rm(dir, { recursive: true, force: true });
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, 'Contents.json'), `${JSON.stringify({ info: XCODE_INFO }, null, 2)}\n`);
    for (const [role, modes] of roles) {
      if (!modes.light || !modes.dark) fail(`colour ${role} needs both a light and a dark value`);
      const colors = Object.keys(APPEARANCES)
        .filter((mode) => modes[mode])
        .map((mode) => {
          const { r, g, b, alpha } = modes[mode];
          const color = {
            'color-space': 'srgb',
            components: { alpha: alpha.toFixed(3), blue: hexByte(b), green: hexByte(g), red: hexByte(r) },
          };
          const appearances = APPEARANCES[mode];
          return { ...(appearances.length ? { appearances } : {}), color, idiom: 'universal' };
        });
      const set = join(dir, `${role}.colorset`);
      await mkdir(set);
      await writeFile(join(set, 'Contents.json'), `${JSON.stringify({ colors, info: XCODE_INFO }, null, 2)}\n`);
    }
  },
  undo: async (_dictionary, platform) => rm(colorsetsDir(platform), { recursive: true, force: true }),
};

const sd = new StyleDictionary({
  source: [join(here, 'tokens/*.json')],
  parsers: ['cox/mode'],
  log: { warnings: 'error' },
  hooks: {
    parsers: {
      'cox/mode': {
        pattern: /\/color\.[^/]+\.json$/,
        parser: ({ contents, filePath }) => {
          const mode = filePath.match(/color\.([^/]+)\.json$/)[1];
          if (!(mode in APPEARANCES)) fail(`${filePath}: unknown colour mode ${mode}`);
          return { [mode]: JSON.parse(contents) };
        },
      },
    },
    formats: { 'cox/swift': swiftFormat, 'cox/css': cssFormat },
    actions: { 'cox/colorsets': colorsets },
  },
  platforms: {
    // Only for SD's name-collision check; the formats name tokens from their paths.
    swift: {
      transforms: ['name/kebab'],
      buildPath: swiftDir,
      files: [{ destination: 'Tokens.swift', format: 'cox/swift' }],
      actions: ['cox/colorsets'],
    },
    css: {
      transforms: ['name/kebab'],
      buildPath: cssDir,
      files: [{ destination: 'tokens.css', format: 'cox/css' }],
    },
  },
});

await sd.buildAllPlatforms();
