// swiftlint:disable line_length
// Generated by desktop/design/style-dictionary.config.mjs from desktop/design/tokens (`just desktop-tokens`). Do not edit.
// swift-format-ignore-file

import SwiftUI

/// A text style (DS§3.2): points at 100 % text size, line height as a multiple, tracking in em.
public struct FontToken: Sendable, Hashable {
    public let size: CGFloat
    public let weight: Font.Weight
    public let design: Font.Design
    public let lineHeight: CGFloat
    public let tracking: CGFloat
}

/// One shadow layer of an elevation level (DS§3.4); an inset layer is the top-edge highlight.
public struct ShadowLayer: Sendable, Hashable {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let inset: Bool
}

/// An elevation level (DS§3.4): its shadow layers, bottom first.
public struct ElevationToken: Sendable, Hashable {
    public let layers: [ShadowLayer]
}

public enum Space {
    public static let xxs: CGFloat = 2
    public static let xs: CGFloat = 4
    public static let s: CGFloat = 6
    public static let m: CGFloat = 8
    public static let ml: CGFloat = 10
    public static let l: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let xxl: CGFloat = 20
    public static let xxxl: CGFloat = 24
    public static let huge: CGFloat = 32
    /// An inspector tab's side inset: the mockup's .tabs span padding 9px
    public static let tab: CGFloat = 9
    /// A popover's top inset: the mockup's .tokpop and .appear padding 14px
    public static let popover: CGFloat = 14
    /// The toolbar's trailing inset: the mockup's .toolbar padding-right 14px
    public static let toolbarTrailing: CGFloat = 14
    /// Under the composer: the mockup's .composer margin-bottom 18px
    public static let composerBottom: CGFloat = 18
    /// The welcome hero's gaps (screen 22): the mockup's 14px under the app icon and beside a suggestion card's text
    public static let welcome: CGFloat = 14
}

public enum Radius {
    public static let xs: CGFloat = 4
    public static let s: CGFloat = 6
    public static let m: CGFloat = 8
    public static let l: CGFloat = 10
    public static let xl: CGFloat = 12
    public static let xxl: CGFloat = 14
    public static let panel: CGFloat = 16
    public static let pane: CGFloat = 18
    public static let popover: CGFloat = 20
    public static let window: CGFloat = 22
    /// Badges and inline code: the mockup's border-radius 5px, between xs and s
    public static let badge: CGFloat = 5
    public static let capsule: CGFloat = 999
    /// A legend swatch: the mockup's .legend i and .tokpop .leg i border-radius 2px
    public static let swatch: CGFloat = 2
    /// An inspector tab: the mockup's .tabs span border-radius 7px
    public static let tab: CGFloat = 7
}

public enum Size {
    public static let toolbarHeight: CGFloat = 56
    public static let sidebarWidth: CGFloat = 252
    public static let inspectorWidth: CGFloat = 324
    public static let readingWidth: CGFloat = 760
    public static let paneGap: CGFloat = 8
    public static let capsuleHeight: CGFloat = 32
    public static let buttonHeight: CGFloat = 28
    public static let buttonHeightSmall: CGFloat = 24
    public static let iconTile: CGFloat = 22
    public static let statusDot: CGFloat = 9
    /// The glow around a live StatusDot: the mockup's 0 0 0 3px ring of the soft status colour
    public static let statusDotHalo: CGFloat = 3
    /// An idle StatusDot's ring: the mockup's border 1.5px
    public static let statusDotRing: CGFloat = 1.5
    /// CountBadge's height and least width: the mockup's .cnt line-height 16px
    public static let countBadge: CGFloat = 16
    public static let hairline: CGFloat = 0.5
    /// A quote's bar in the transcript (A97), coloured quote.bar
    public static let quoteBar: CGFloat = 3
    public static let windowMinWidth: CGFloat = 1100
    public static let windowMinHeight: CGFloat = 700
    /// A new session window's width: the mockups' 1440×900 window, clamped to the screen
    public static let windowDefaultWidth: CGFloat = 1440
    /// A new session window's height: the mockups' 1440×900 window, clamped to the screen
    public static let windowDefaultHeight: CGFloat = 900
    public static let popoverWidth: CGFloat = 340
    public static let tokenPopoverWidth: CGFloat = 360
    /// The first-run window: the mockup's .window.small, 980px wide
    public static let windowSmallWidth: CGFloat = 980
    /// A composer chip: the mockup's .chip height 26px
    public static let chipHeight: CGFloat = 26
    /// The composer's round Send: the mockup's .send, 30px
    public static let sendButton: CGFloat = 30
    /// The composer's text area with its insets, at least: the mockup's .composer .ta min-height 46px
    public static let composerTextMinHeight: CGFloat = 46
    /// The composer's completion list: the mockup's .pop, 470px wide
    public static let completionWidth: CGFloat = 470
    /// The command palette: the mockup's .palette, 640px wide (screen 12)
    public static let paletteWidth: CGFloat = 640
    /// A palette row's icon well: the mockup's .palette .ic2, 26px
    public static let paletteIcon: CGFloat = 26
    /// Review's file list: the mockup's 260px column (screen 08)
    public static let reviewFileListWidth: CGFloat = 260
    /// The welcome hero's app icon (screen 22): the mockup's .appicon, 56px
    public static let appIconHero: CGFloat = 56
    /// Above the welcome hero (screen 22): the mockup's .reading padding-top 170px
    public static let welcomeTop: CGFloat = 170
    /// A prompt's turn number in the gutter (screens 01, 14): the mockup's .gutter, 32px wide
    public static let turnGutter: CGFloat = 32
    /// From the gutter's leading edge to the bubble (screens 01, 14): the mockup's .gutter left -44px
    public static let turnGutterOffset: CGFloat = 44
    /// A prompt's rewind scope menu (screen 14): the mockup's .popover, 330px wide
    public static let rewindMenuWidth: CGFloat = 330
}

public extension FontToken {
    /// Session title in the toolbar
    static let titleWindow = FontToken(size: 13.5, weight: .semibold, design: .default, lineHeight: 1.3, tracking: 0)
    /// Settings page title: the mockup's .set-main h1, 20px bold
    static let titlePage = FontToken(size: 20, weight: .bold, design: .default, lineHeight: 1.45, tracking: 0)
    /// First-run window title: the mockup's 26px bold h1 (screen 21)
    static let titleHero = FontToken(size: 26, weight: .bold, design: .default, lineHeight: 1.45, tracking: 0)
    /// Settings group box title: the mockup's .gtitle, 12px semibold
    static let titleGroup = FontToken(size: 12, weight: .semibold, design: .default, lineHeight: 1.45, tracking: 0)
    /// Session row title in the sidebar: the mockup's .row .t, 13px medium
    static let titleSession = FontToken(size: 13, weight: .medium, design: .default, lineHeight: 1.45, tracking: 0)
    /// The command palette's query: the mockup's .palette .q, 18px regular (screen 12)
    static let titlePalette = FontToken(size: 18, weight: .regular, design: .default, lineHeight: 1.3, tracking: 0)
    /// The welcome hero's question (screen 22): the mockup's h2, 20px bold
    static let titleWelcome = FontToken(size: 20, weight: .bold, design: .default, lineHeight: 1.3, tracking: 0)
    /// A welcome suggestion's title (screen 22): the mockup's .card b, 13px bold
    static let titleCard = FontToken(size: 13, weight: .bold, design: .default, lineHeight: 1.45, tracking: 0)
    /// Default UI text
    static let body = FontToken(size: 13, weight: .regular, design: .default, lineHeight: 1.45, tracking: 0)
    /// Assistant and user messages
    static let transcript = FontToken(size: 13.5, weight: .regular, design: .default, lineHeight: 1.55, tracking: 0)
    /// Level-1 Markdown headings in the transcript (DT§5.9, A94)
    static let transcriptH1 = FontToken(size: 17, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Level-2 Markdown headings in the transcript (DT§5.9, A94)
    static let transcriptH3 = FontToken(size: 15, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Level-3 Markdown headings in the transcript, and levels 4-6, which DT§5.9 does not size (A94)
    static let transcriptH4 = FontToken(size: 13, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Buttons, capsules, segmented items
    static let control = FontToken(size: 12.5, weight: .medium, design: .default, lineHeight: 1.2, tracking: 0)
    /// Thinking line, notices
    static let caption = FontToken(size: 12, weight: .regular, design: .default, lineHeight: 1.4, tracking: 0)
    /// Tool status, meter, key-value rows
    static let footnote = FontToken(size: 11.5, weight: .regular, design: .default, lineHeight: 1.4, tracking: 0)
    /// Dense rows: inspector file and plan rows, the decision bar, the cost capsule's context (the mockup's 12.5px regular)
    static let compact = FontToken(size: 12.5, weight: .regular, design: .default, lineHeight: 1.45, tracking: 0)
    /// Segment and inspector tab labels: the mockup's .seg span and .tabs span, 12px medium
    static let segment = FontToken(size: 12, weight: .medium, design: .default, lineHeight: 1.2, tracking: 0)
    /// The Stop button's label: the mockup's .stop, 12px semibold
    static let stop = FontToken(size: 12, weight: .semibold, design: .default, lineHeight: 1.2, tracking: 0)
    /// Second lines: a session row's subtitle and cost, the token popover's rate line and note (the mockup's 11px regular)
    static let detail = FontToken(size: 11, weight: .regular, design: .default, lineHeight: 1.45, tracking: 0)
    /// The token popover's legend: the mockup's .tokpop .leg, 10px regular
    static let legend = FontToken(size: 10, weight: .regular, design: .default, lineHeight: 1.45, tracking: 0)
    /// Uppercase section headers
    static let label = FontToken(size: 11, weight: .semibold, design: .default, lineHeight: 1.3, tracking: 0.03)
    /// Key caps, legends, badges
    static let micro = FontToken(size: 10.5, weight: .medium, design: .default, lineHeight: 1.3, tracking: 0)
    /// Big numbers (tok/s); tabular digits
    static let metric = FontToken(size: 26, weight: .semibold, design: .default, lineHeight: 1, tracking: -0.02)
    /// Code blocks, diffs
    static let monoCode = FontToken(size: 12, weight: .regular, design: .monospaced, lineHeight: 1.55, tracking: 0)
    /// Inline code in prose
    static let monoInline = FontToken(size: 12, weight: .regular, design: .monospaced, lineHeight: 1.3, tracking: 0)
    /// Terminal tail
    static let monoTerminal = FontToken(size: 11.5, weight: .regular, design: .monospaced, lineHeight: 1.5, tracking: 0)
    /// The command in an approval card's well: the mockup's .appr .cmd, 12.5px
    static let monoCommand = FontToken(size: 12.5, weight: .regular, design: .monospaced, lineHeight: 1.45, tracking: 0)
    /// The app icon's cx (screens 22, 23): the mockup's .appicon, 22px (800 there; bold is the heaviest weight the token pipeline maps), letter-spacing -1px
    static let monoAppIcon = FontToken(size: 22, weight: .bold, design: .monospaced, lineHeight: 1, tracking: -0.045)
}

public extension ElevationToken {
    /// Flat: transcript prose, collapsed tool rows
    static let e0 = ElevationToken(layers: [])
    /// Chips, capsules, icon tiles, selected row
    static let e1 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.1), x: 0, y: 1, blur: 2, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.08), x: 0, y: 4, blur: 10, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Cards: user bubble, expanded tool, sidebar, inspector
    static let e2 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.1), x: 0, y: 2, blur: 4, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.14), x: 0, y: 10, blur: 26, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Composer: the one thing that floats highest in a pane
    static let e3 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.14), x: 0, y: 4, blur: 10, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.26), x: 0, y: 24, blur: 60, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Popovers and menus
    static let e4 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.17), x: 0, y: 8, blur: 20, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.33), x: 0, y: 30, blur: 70, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1), x: 0, y: 1, blur: 0, spread: 0, inset: true),
    ])
    /// The window over the wallpaper
    static let e5 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 8 / 255, green: 10 / 255, blue: 40 / 255, opacity: 0.3), x: 0, y: 16, blur: 40, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 8 / 255, green: 10 / 255, blue: 40 / 255, opacity: 0.55), x: 0, y: 50, blur: 120, spread: 0, inset: false),
    ])
}

public enum Motion {
    /// Hover, press
    public static let durationFast: TimeInterval = 0.12
    /// Disclosure expand/collapse
    public static let durationBase: TimeInterval = 0.2
    /// Popover, sheet, pane slide
    public static let durationSlow: TimeInterval = 0.32
    /// Most transitions
    public static let easingStandard: UnitCurve = .bezier(startControlPoint: UnitPoint(x: 0.2, y: 0), endControlPoint: UnitPoint(x: 0, y: 1))
    /// Things entering
    public static let easingDecelerate: UnitCurve = .bezier(startControlPoint: UnitPoint(x: 0, y: 0), endControlPoint: UnitPoint(x: 0.2, y: 1))
}

public enum MaterialToken {
    public static let frostedWindowOpacity: Double = 0.42
    public static let frostedBlur: Double = 34
    public static let frostedSaturation: Double = 1.9
    public static let frostedSpecular: Double = 0.35
    public static let glossyWindowOpacity: Double = 0.3
    public static let glossyBlur: Double = 6
    public static let glossySaturation: Double = 1.9
    public static let glossySpecular: Double = 0.55
    public static let solidWindowOpacity: Double = 1
    public static let solidBlur: Double = 0
    public static let solidSaturation: Double = 1
    public static let solidSpecular: Double = 0
    public static let readableFloorWindowOpacity: Double = 0.8
    public static let highContrastGlassKeep: Double = 0.25
    /// Dark mode, `dark_highlight = none`: no top-edge highlight, the dark mockup's look (A109)
    public static let darkHighlightNone: Double = 0
    /// Dark mode, `dark_highlight = subtle`: the highlight at this share of the light one's strength (A109)
    public static let darkHighlightSubtle: Double = 0.1
}

// swiftlint:enable line_length
