[package]
name = "cox-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ignore = { workspace = true }
grep-searcher = { workspace = true }
grep-regex = { workspace = true }
globset = { workspace = true }
nucleo = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
