//! Hand-written to match `migrations/00000000000001_init/up.sql` exactly
//! (plan.md §1.7/D9: "`schema.rs` is generated by `diesel print-schema`
//! and committed [...] a test asserts it matches the migrations"). Written
//! by hand here rather than via the `diesel_cli` binary; `schema_snapshot_matches`
//! (lib.rs) compares the live `sqlite_master` SQL against a committed insta
//! snapshot, so drift between this file and the DDL still fails a test even
//! without the generator.
//!
//! FTS5 virtual tables (`memory_fts`, `rollout_fts`) have no `table!` entry:
//! Diesel cannot model `VIRTUAL TABLE`, so they are created in `up.sql` and
//! queried through `diesel::sql_query` + `QueryableByName` instead (D9).

diesel::table! {
    /// App-level migration ledger declared in the DDL (plan.md §1.7).
    /// Unused by `diesel_migrations`, which tracks its own bookkeeping table;
    /// no `cox-store` code reads or writes this yet.
    migrations (version) {
        version -> Integer,
        applied_at -> Text,
    }
}

diesel::table! {
    sessions (id) {
        id -> Text,
        created_at -> Text,
        updated_at -> Text,
        cwd -> Text,
        project_slug -> Text,
        title -> Nullable<Text>,
        parent_id -> Nullable<Text>,
        rollout_path -> Text,
        turns -> Integer,
        cost_usd -> Double,
        state -> Text,
        title_source -> Nullable<Text>,
        agent -> Nullable<Text>,
        agent_session -> Nullable<Text>,
    }
}

diesel::table! {
    usage (id) {
        id -> Integer,
        session_id -> Text,
        turn -> Integer,
        job -> Text,
        tier -> Text,
        provider -> Text,
        model -> Text,
        input_tokens -> BigInt,
        output_tokens -> BigInt,
        cache_read_tokens -> BigInt,
        cache_write_tokens -> BigInt,
        estimated -> Bool,
        cost_usd -> Double,
        latency_ms -> BigInt,
        context_tokens -> BigInt,
        created_at -> Text,
        effort -> Nullable<Text>,
    }
}

diesel::table! {
    archive (id) {
        id -> Text,
        session_id -> Text,
        call_id -> Text,
        tool -> Text,
        subject -> Nullable<Text>,
        bytes -> BigInt,
        sha256 -> Text,
        inline -> Nullable<Binary>,
        path -> Nullable<Text>,
        created_at -> Text,
    }
}

diesel::table! {
    memory (id) {
        id -> Integer,
        project_slug -> Text,
        name -> Text,
        path -> Text,
        kind -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    /// `00000000000003_checkpoints` (T26.1).
    checkpoints (id) {
        id -> Integer,
        session_id -> Text,
        turn -> Integer,
        call_id -> Nullable<Text>,
        path -> Text,
        kind -> Text,
        archive_id -> Nullable<Text>,
        created_at -> Text,
    }
}

diesel::table! {
    /// `00000000000004_plugins` (T33.5, PL§3): the grant approved for one
    /// plugin id at one package digest, in one scope (`user` or
    /// `project:<root>`, stored as text — `Store` converts to/from
    /// `GrantScope`). `capabilities` and `source` are JSON text.
    plugin_grants (plugin_id, scope, digest) {
        plugin_id -> Text,
        scope -> Text,
        digest -> Text,
        capabilities -> Text,
        enabled -> Bool,
        source -> Text,
        decided_at -> Text,
    }
}

diesel::table! {
    /// `00000000000004_plugins` (T33.5, PL§3): the per-plugin key-value
    /// store, the only state that outlives a call (extism's own vars are
    /// off, P12). Quota is enforced in `Store`, not the schema.
    plugin_kv (plugin_id, key) {
        plugin_id -> Text,
        key -> Text,
        value -> Binary,
        updated_at -> Text,
    }
}

diesel::table! {
    /// `00000000000007_cloud_runs` (T56.5, P56): one row per hosted
    /// cloud-agent run, keyed by backend and the backend's run id.
    cloud_runs (backend, run_id) {
        backend -> Text,
        run_id -> Text,
        session_id -> Text,
        task_id -> Text,
        agent_id -> Text,
        repository -> Text,
        model -> Nullable<Text>,
        status -> Text,
        terminal -> Bool,
        usage_recorded -> Bool,
        created_at -> Text,
        updated_at -> Text,
    }
}

// `usage` joins `sessions` on `session_id` (no foreign key in the DDL, so no
// `joinable!`): the project spend in `queries.rs` groups by the session's cwd.
diesel::allow_tables_to_appear_in_same_query!(sessions, usage);
