#!/bin/bash
# Copyright (c) 2026 Ivan Tugay
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under GPL-3.0 or later; see https://www.gnu.org/licenses/gpl-3.0.html

#
# Print the Homebrew cask for one cox release.
#
#   scripts/cask.sh <version> <sha256-aarch64>
#
# macOS is Apple Silicon only, so the cask has one (arm64) archive.
#
# The release workflow writes the output to Casks/cox.rb in pyrlyn/homebrew-tap
# on every release, so the file there is generated, never edited by hand: change
# this script instead.

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 <version> <sha256-aarch64>" >&2
  exit 2
fi

VERSION="${1#v}"
SHA_ARM="$2"

if ! printf '%s' "$SHA_ARM" | grep -Eq '^[0-9a-f]{64}$'; then
  echo "not a sha256: $SHA_ARM" >&2
  exit 2
fi

cat <<EOF
# Generated by scripts/cask.sh in pyrlyn/cox on every release. Do not edit:
# the next release overwrites this file. Change scripts/cask.sh instead.
cask "cox" do
  version "${VERSION}"
  sha256 "${SHA_ARM}"

  url "https://github.com/pyrlyn/cox/releases/download/v#{version}/cox-aarch64-apple-darwin.tar.xz"
  name "cox"
  desc "Modular terminal coding agent"
  homepage "https://github.com/pyrlyn/cox"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  depends_on arch: :arm64

  # cox installs into ~/.local/bin via install.sh; Homebrew only delivers the
  # tarball. Nothing is linked into the prefix.
  stage_only true

  postflight do
    set_ownership "\#{staged_path}/cox"
  end

  uninstall delete: "\#{staged_path}/cox"

  zap trash: "~/.cox"
end
EOF